// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ritvlsjispdxkxummhrf.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJpdHZsc2ppc3BkeGt4dW1taHJmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTMzODIxNTYsImV4cCI6MjA2ODk1ODE1Nn0.GDAQi1x8qQiuAjgdGm8JHQemPywuJtxuwnkbkDLvOWA";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});